[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
health_fun = "AurTvci86g6Wx95U93zQtonzV3CwHq7Ehpw9chS1oqCa"

[programs.localnet]
health_fun = "AurTvci86g6Wx95U93zQtonzV3CwHq7Ehpw9chS1oqCa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run test:codama"
