[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
health_fun = "7k8STpaJxptrSVn8BLRDw1CgqGMZoU8iVUjkzHA9oCdp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run test:codama"
