[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
health_fun = "DADe3TShkZZnA8hvpMMUNmgGDe7LGwQbXZ2KDe2hTTXJ"

[programs.devnet]
health_fun = "DADe3TShkZZnA8hvpMMUNmgGDe7LGwQbXZ2KDe2hTTXJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run test:codama"
